Use GitHub workflows instead of travis.org for CI and publishing.
w3c/FileAPI pull request #160
Opened 2021-01-22 00:36 UTC by mkruisselbrink

2021-01-22 00:37 UTC, mkruisselbrink commented
This doesn't currently do w3c publishing yet, since afaik the w3c spec-prod github action doesn't support that for bikeshed specs yet. Since we probably don't want to lose that, we should hold of on merging this...

2021-04-19 07:52 UTC, annevk commented
Maybe @sideshowbarker can help with this as he recently converted a bunch of repos.

2021-04-19 08:49 UTC, sideshowbarker requested changes
With the suggested commit applied, this should work as-is

2021-04-19 08:49 UTC, sideshowbarker commented on .github/workflows/pr-push.yml
> +      - uses: sidvishnoi/spec-prod@v1
```suggestion
      - uses: w3c/spec-prod@v2
```

2021-04-19 08:52 UTC, sideshowbarker approved these changes

2021-04-19 08:52 UTC, merged

2021-04-20 03:04 UTC, mkruisselbrink commented
I think this is still missing the auto-publishing as WD? Or does that not need some configuration as well?

2021-04-20 04:49 UTC, sideshowbarker commented
> I think this is still missing the auto-publishing as WD? Or does that not need some configuration as well?

Yeah it needs a couple more lines in the config file. But I’ve now added them, in https://github.com/w3c/FileAPI/pull/167.